### PR TITLE
Simplify tmuxline (remove much utf-8).

### PR DESCRIPTION
**Pull request by raymondberg**
Would like to use a simpler and more cross-platform config for tmuxline. The previous was unstable/unusable on gnome terminal.

### CODE REVIEW

**Comment by dewyze** [comment]
I think I would be okay with this if we could find a way to easily have a tmuxline.conf local? I use this [patched font](https://gist.github.com/baopham/1838072) and OS X and there is a way to do it more easily on linux machines, I don't remember offhand what that is. Any thoughts?

**Comment by raymondberg** [comment]
Is there any reason to leave the UTF-8 stuff in there? Even aesthetically I find this more pleasant.

**Comment by dewyze** [comment]
I think I am having issues understanding what is happening.

Currently, when I start a tmux I see this:
normal

If I open vim after that I see this:
normal vim

In your refactor, if I open tmux I see this:
rays

However, if I open vim in that same tmux, I see this:
rays after vim

I would think that none of this is right? I am not sure how it changes my tmux "back" to the old way when vim starts, but in the beginning looks...that different?

Thoughts?

**Comment by dewyze** [comment]
Goodbye airline. We hardly knew ye. :cry: 

:+1:

**Comment by raymondberg** [comment]
I sucked the issue you're having into a separate Issue: https://github.com/dewyze/dotfiles/issues/7

I believe in the dream of airliner. Just not today :boot:

**Pull request merged**
