### PR TITLE
Slim refactor

### PR DESCRIPTION
**Pull request by raymondberg**
## Changelog:
- Wanted to explain the repo a bit more and de-Dewzy it a bit. 
- Rewrote/organized the core shell configs to make them easier to maintain and more standard between the environments. 
- Removed duplicated path entries by switching to standard `safepathappend/prepend` model. 
- Standardized away from ~ to use $HOME which is more conventional and universally accepted in various commands and inside strings
- Bugfix - Add switch for mouse modes based on version ( currently throws error in tmux 2.1)

Tested MAC Yosemite and Ubuntu 14.04 LTS

### CODE REVIEW

**Comment by dewyze** [comment]
This is so pretty... :smile: :grinning: :laughing: :sob:

**Comment by dewyze** [comment]
@raymondberg what are your thoughts on this: http://www.zsh.org/mla/users/2015/msg00725.html

**Comment by raymondberg** [comment]
I'm open to it; I haven't done the migration yet.

**Comment by raymondberg** [comment]
I'm open to it, I haven't done the migration yet.

Respectfully,
Ray Berg

**Comment by dewyze** [comment]
I will admit I am not totally sure of the repercussions, but we are modifying the $PATH in the `zshenv`. I think I may just add it?

Can you test if it mucks up anything on your non El Capitan?

**Comment by dewyze** [comment]
Hmmm....it make break Ubuntu though. I will investigate further. Thanks for the cleanup.

**Pull request merged**
